
CREATE TABLE SINGER(
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(60) NOT NULL,
  LAST_NAME VARCHAR(40) NOT NULL,
  BIRTH_DATE DATE,
  VERSION INT NOT NULL DEFAULT 0,
  UNIQUE UQ_NAME (FIRST_NAME, LAST_NAME),
  PRIMARY KEY (ID)
);

CREATE TABLE ALBUM (
  ID INT NOT NULL AUTO_INCREMENT,
  SINGER_ID INT NOT NULL,
  TITLE VARCHAR(100) NOT NULL,
  RELEASE_DATE DATE,
  VERSION INT NOT NULL DEFAULT 0,
  UNIQUE UQ_SINGER_ALBUM (SINGER_ID, TITLE),
  PRIMARY KEY(ID),
  CONSTRAINT FK_ALBUM_SINGER
  FOREIGN KEY (SINGER_ID)
  REFERENCES SINGER(ID)
);

CREATE TABLE INSTRUMENT (
  INSTRUMENT_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (INSTRUMENT_ID)
);

CREATE TABLE SINGER_INSTRUMENT (
  SINGER_ID INT NOT NULL,
  INSTRUMENT_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (SINGER_ID, INSTRUMENT_ID),
  CONSTRAINT FK_SINGER_INSTRUMENT
  FOREIGN KEY (SINGER_ID)
  REFERENCES SINGER(ID) ON DELETE CASCADE,
  CONSTRAINT FK_INSTRUMENT_SINGER
  FOREIGN KEY (INSTRUMENT_ID)
  REFERENCES INSTRUMENT(INSTRUMENT_ID)
);

INSERT INTO SINGER(FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Siwoo', 'Kim', '1989-03-04');

INSERT INTO SINGER(FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Eric', 'Clapton', '1945-03-30');

INSERT INTO SINGER(FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('John', 'Butler', '1975-04-01');

INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE)
VALUES (1, 'The Search for Everything', '2017-01-20');

INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE)
VALUES (1, 'Battle Studies', '2009-11-17');

INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE)
VALUES (2, 'From The Cradle', '1994-09-13');

INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE)
VALUES (1, 'New Album1 ', '2017-03-20');

INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE)
VALUES (1, 'New Album2', '2018-01-17');

INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE)
VALUES (2, 'Cool Album1', '2017-03-04');

INSERT INTO INSTRUMENT (INSTRUMENT_ID) VALUES ('Guitar');
INSERT INTO INSTRUMENT (INSTRUMENT_ID) VALUES ('Piano');
INSERT INTO INSTRUMENT (INSTRUMENT_ID) VALUES ('Voice');
INSERT INTO INSTRUMENT (INSTRUMENT_ID) VALUES ('Drums');
INSERT INTO INSTRUMENT (INSTRUMENT_ID) VALUES ('Synthesizer');

INSERT INTO SINGER_INSTRUMENT(SINGER_ID, INSTRUMENT_ID) VALUES (1, 'Guitar');
INSERT INTO SINGER_INSTRUMENT(SINGER_ID, INSTRUMENT_ID) VALUES (1, 'Piano');
INSERT INTO SINGER_INSTRUMENT(SINGER_ID, INSTRUMENT_ID) VALUES (2, 'Guitar');
